# Generated by Django 4.1.9 on 2023-06-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.json_extended


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_room_options_room_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_names', models.JSONField(decoder=mysite.json_extended.ExtendedJsonDecoder, default=set, encoder=mysite.json_extended.ExtendedJsonEncoder)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='online_user_set',
            field=models.ManyToManyField(blank=True, related_name='joined_room_set', through='chat.RoomMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
